# Routes
url: https://brandonb.ca
assets_root: https://dc1r9kxqg42ml.cloudfront.net
assets_media: https://dc1r9kxqg42ml.cloudfront.net/brandonb.ca

debug: false

# Publishing
future: false
show_drafts: false

# Build settings
exclude:
  [
    "gulp_tasks",
    "build_dev",
    "api_data",
    ".ruby-version",
    ".editorconfig",
    "package.json",
    "package-lock.json",
    "gulpfile.babel.js",
    "README.md",
  ]
