encoding: 'utf-8'
language: 'en-us'

# Site Settings
title: 'Brandons Blog'
author:
  name: 'Brandon Brown'
  email: 'brandon@brandonb.io'
description: > # ignore newlines in this value
  Canadian with a passion for open source, tech, and front-end web development.
  <br/>Checkout my podcast <a href="http://faviconvalley.show">Favicon Valley</a>
meta_description: Product Developer at sendwithus, host of Favicon Valley podcast.

# Favicons
favicon:
  ico: https://dl.dropboxusercontent.com/u/3408044/brandonb.io/favicon.ico
  png: https://dl.dropboxusercontent.com/u/3408044/brandonb.io/logo-144.png
  theme_color: '#FFFFFF'

# Routes
baseurl: '' # Use if your site is in a subdirectory, e.g. /blog/
root: /
permalink: /:title

assets_images: /assets/images
assets_scripts: /assets/scripts
assets_styles: /assets/styles

# Writing
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Build-stuff
keep_files: [
  'assets',
  'foursquare.json']

# Pagination
paginate: 5
paginate_path: /page/:num

defaults:
  -
    scope:
      path: ''
      type: posts
    values:
      layout: post

# 3rd-party
social:
  twitter: brandonb927
  github: brandonb927
  googleplus: brandonbrown927

disqus:
  shortname: brandonbrownsblog

google_analytics:
  id: UA-32422940-2
  domain: brandonb.io

# Extras
gems:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
