# Routes
url: "http://localhost:8888"

# Publishing
show_drafts: true
future: true

# Disable some things for development
google_analytics:
  id: false
  domain: false

google_ads:
  id: false

# Build settings
keep_files: [
  'assets',
  'api'
]

exclude: [
  'gulp_tasks',
  'build_prod',
  'api_data',
  '.ruby-version',
  '.editorconfig',
  'package.json',
  'package-lock.json',
  'gulpfile.babel.js',
  'README.md'
]
