# Routes
url: https://brandonb.ca
assets_root: https://dc1r9kxqg42ml.cloudfront.net
assets_media: https://dc1r9kxqg42ml.cloudfront.net/brandonb.ca

debug: false

# Publishing
future: false
show_drafts: false

# Build settings
exclude: [
  'node_modules',
  'gulp_tasks',
  'build_dev',
  'api_data',
  '.ruby-version',
  '.editorconfig',
  'Gemfile',
  'Gemfile.lock',
  'package.json',
  'yarn.lock',
  'gulpfile.babel.js',
  'README.md'
]
