encoding: 'utf-8'
language: 'en-us'

# Site Settings
title: 'Brandons Blog'
author:
  name: 'Brandon Brown'
  email: 'brandon@brandonb.ca'
description: Canadian with a passion for <br />open source, tech, and front-end web development
meta_description: Brandon Brown, Product QA Developer

# Favicons
favicon:
  ico: /favicon.ico
  png: /logo-144.png
  theme_color: '#FFFFFF'

break_tag: '<!-- break -->'

# Routes
permalink: /:title

assets_root: ''
assets_media: /assets/media
assets_scripts: /assets/scripts
assets_styles: /assets/styles

# Writing
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Build-stuff
keep_files: [
  'assets',
  'api']

defaults:
  -
    scope:
      path: ''
      type: posts
    values:
      layout: post
  -
    scope:
      path: ''
      type: projects
    values:
      layout: page

collections:
  projects:
    output: true

# 3rd-party
social:
  github: brandonb927
  twitter: brandonb927
  instagram: brandonb.927
  unsplash: brandonb927

google_analytics:
  id: UA-32422940-2
  domain: brandonb.ca

# Extras
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
