# Routes
url: "http://localhost:8888"

# Publishing
future: true
show_drafts: true

# Disable some things for development
google_analytics:
  id: false
  domain: false

# Build settings
exclude: [
  'node_modules',
  'gulp_tasks',
  'build_prod',
  '.ruby-version',
  '.editorconfig',
  'Gemfile',
  'Gemfile.lock',
  'package.json',
  'package-lock.json',
  'gulpfile.babel.js',
  'README.md'
]
