# Routes
url: https://brandonb.io
assets_images: https://d3b5kx8qsv0rui.cloudfront.net

debug: false

# Publishing
future: false
show_drafts: false

exclude: [
  '.ruby-version',
  '.editorconfig',
  'gulpfile.babel.js',
  'Gemfile',
  'Gemfile.lock',
  'package.json',
  'README.md',
  'node_modules',
  'gulp_tasks',
  'build_dev']
