encoding: "UTF-8"
language: "en-us"

# Site Settings
title: Brandon's Blog
author:
  name: Brandon Brown
  email: brandon@brandonb.ca
description: A Canadian with a passion for <br />open source, tech, web development, and amateur radio
meta_description: Brandon Brown — Canadian with a passion for open source, tech, web development, and amateur radio
avatar_img: /avatar20_512.jpg

# Favicons
favicon:
  ico: /favicon.ico
  png: /logo-144.png
  theme_color: "#FFFFFF"

excerpt_separator: "<!-- break -->"

# Routes
permalink: /:title

assets_root: ""
assets_media: /assets/media
assets_scripts: /assets/scripts
assets_styles: /assets/styles

# Writing
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Build-stuff
keep_files: ["assets", "api"]

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      is_post: true
  - scope:
      path: ""
      type: projects
    values:
      layout: page
      is_post: false

collections:
  projects:
    output: true

footer_links:
  - title: GitHub
    url: https://github.com/brandonb927
  - title: Mastodon
    url: https://mastodon.hams.social/@ve7tzb
    attrs: 'rel="me"'
  - title: Flickr
    url: https://flickr.com/photos/brandonb927
  - title: RSS
    url: /feed.xml

amazon_associates_tag: brandonb0a-20

# Plugins
plugins:
  - jekyll-responsive-image

# responsive_image config
responsive_image:
  cache: true

  template: _includes/responsive_image.html

  default_quality: 100

  strip: true

  sizes:
    - width: 480
    - width: 720
    - width: 1440

  output_path_format: assets/media/r/%{filename}-%{width}x%{height}.%{extension}

  save_to_source: false
