encoding: "UTF-8"
language: "en-us"

# Site Settings
title: VE7TZB
author:
  name: VE7TZB
description: VE7TZB home on the web
meta_description: An amateur radio-focused web site by callsign VE7TZB
avatar_img: /tmv71a.jpg

# Favicons
favicon:
  ico: /favicon.ico
  png: /logo-144.png
  theme_color: "#FFFFFF"

excerpt_separator: "<!-- break -->"

# Routes
permalink: /:title

assets_root: ""
assets_media: /assets/media
assets_scripts: /assets/scripts
assets_styles: /assets/styles

# Writing
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Build-stuff
keep_files: ["assets"]

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      is_post: true
  - scope:
      path: ""
      type: projects
    values:
      layout: page
      is_post: false
  - scope:
      path: ""
      type: qso
    values:
      layout: page
      is_post: false

collections:
  projects:
    output: true
  qso:
    output: true

footer_links:
  - title: mastodon.hams.social
    url: https://mastodon.hams.social/@ve7tzb
    attrs: 'rel="me"'
  - title: mastodon.radio
    url: https://mastodon.radio/@ve7tzb
    attrs: 'rel="me"'

# google_analytics:
#   id: G-7P078D4S4Q
#   domain: ve7tzb.ca

# google_ads:
#   id: ca-pub-5686888191550897
#   publisher_id: pub-5686888191550897

amazon_associates_tag: brandonb0a-20

# Plugins
# plugins:
#   - jekyll-responsive-image

# responsive_image config
# responsive_image:
#   cache: true

#   template: _includes/responsive_image.html

#   default_quality: 100

#   strip: true

#   sizes:
#     - width: 480
#     - width: 720
#     - width: 1440

#   output_path_format: assets/media/r/%{filename}-%{width}x%{height}.%{extension}

#   save_to_source: false
