encoding: "UTF-8"
language: "en-us"

# Site Settings
title: VE7TZB
author:
  name: Brandon VE7TZB
description: VE7TZB, an Amateur Radio Operator in BC, Canada
meta_description: VE7TZB, an Amateur Radio Operator in BC, Canada
avatar_img: /avatar.png

# Favicons
favicon:
  ico: /favicon.ico
  png: /apple-touch-icon.png

excerpt_separator: "<!-- break -->"

# Routes
permalink: /:title

assets_root: ""
assets_media: /assets/media
assets_scripts: /assets/scripts
assets_styles: /assets/styles

# Writing
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Build-stuff
keep_files: ["assets"]

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      is_post: true
  - scope:
      path: ""
      type: projects
    values:
      layout: page
      is_post: false
  - scope:
      path: ""
      type: qso
    values:
      layout: page
      is_post: false

collections:
  projects:
    output: true
  qso:
    output: true

nav_links:
  - title: mastodon.hams.social
    url: https://mastodon.hams.social/@ve7tzb
    attrs: 'rel="me" target="_blank"'
  - title: RSS
    url: /feed.xml
    attrs: ''

amazon_associates_tag: brandonb0a-20

# Plugins
# plugins:
#   - jekyll-responsive-image

# responsive_image config
# responsive_image:
#   cache: true

#   template: _includes/responsive_image.html

#   default_quality: 100

#   strip: true

#   sizes:
#     - width: 480
#     - width: 720
#     - width: 1440

#   output_path_format: assets/media/r/%{filename}-%{width}x%{height}.%{extension}

#   save_to_source: false
