# Routes
domain: ve7ztb.ca
url: https://ve7ztb.ca
assets_root: https://dc1r9kxqg42ml.cloudfront.net
assets_media: https://dc1r9kxqg42ml.cloudfront.net/ve7ztb.ca

debug: false

# Publishing
future: false
show_drafts: false

# Build settings
exclude:
  [
    "gulp_tasks",
    "build_dev",
    "gulpfile.babel.js",
    "README.md",
  ]
