# Routes
domain: localhost
url: "http://localhost:8888"

# Publishing
show_drafts: true
future: true

# Build settings
keep_files: ["assets"]

exclude:
  [
    "gulp_tasks",
    "build_prod",
    "gulpfile.babel.js",
    "README.md",
  ]
