name: Build and Deploy Sites

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  build-brandonb_ca:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-brandonb.ca-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-brandonb.ca-

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3'

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache-dependency-path: 'package-lock.json'

      - name: Install ruby dependencies
        run: gem install bundler && bundle install

      - name: Install js dependencies
        run: npm ci

      - name: Build and deploy brandonb.ca
        run: npm run brandonb.ca:deploy:dryrun
